// Auto-generated by tools/generate_bank_field_schemas.py. Do not edit manually.

export type BankFieldSchema = {
  bankCode: string;
  parserClasses: string[];
  parserFiles: string[];
  aliases: string[];
  transactionFields: string[];
  metadataFields: string[];
  statementMetadataFields: string[];
};

import HDFCSchema from './bank-field-schemas/HDFC.json';
import IDIBSchema from './bank-field-schemas/IDIB.json';
import JIOPSchema from './bank-field-schemas/JIOP.json';
import KKBKSchema from './bank-field-schemas/KKBK.json';
import MAHBSchema from './bank-field-schemas/MAHB.json';
import SBINSchema from './bank-field-schemas/SBIN.json';
import UTIBSchema from './bank-field-schemas/UTIB.json';
import YESBSchema from './bank-field-schemas/YESB.json';

export const bankFieldSchemas: BankFieldSchema[] = [
  HDFCSchema as BankFieldSchema,
  IDIBSchema as BankFieldSchema,
  JIOPSchema as BankFieldSchema,
  KKBKSchema as BankFieldSchema,
  MAHBSchema as BankFieldSchema,
  SBINSchema as BankFieldSchema,
  UTIBSchema as BankFieldSchema,
  YESBSchema as BankFieldSchema
];

export const bankFieldSchemaMap: Record<string, BankFieldSchema> = Object.fromEntries(
  bankFieldSchemas.map((schema) => [schema.bankCode, schema])
);
